### ISSUE TITLE
Support for more than just MySQL

### ISSUE THREAD

**Issue by n-tdi** [IllusionTheDev/Cosmos#8]
Hey Illusion, 

MySQL is a proprietary database structure, is there the possibility to add support for Postgresql or MariaDB? 

I could look into making my own PR, but am a bit time crunched ATM.

**Comment by IllusionTheDev** [comment]
Hey there, do the queries change at all? It's most likely just a basic driver change, so it shouldn't be hard at all

**Comment by IllusionTheDev** [comment]
e0fe121 Should be done

**Comment by n-tdi** [comment]
Thanks LGTM
